/*
 * This file was generated by the Gradle 'init' task.
 *
 */

plugins {
    id("org.jetbrains.kotlin.jvm").version("1.3.20")
    groovy

    application
}

repositories {
    jcenter()

}


dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    //Spock tests
    testImplementation("org.codehaus.groovy:groovy-all:2.4.15")
    testImplementation("org.spockframework:spock-core:1.2-groovy-2.4")
    testImplementation("org.codehaus.groovy.modules.http-builder:http-builder:0.7.1")
    //compile group: 'org.codehaus.groovy.modules.http-builder', name: 'http-builder', version: '0.7.1'

    //Gradle asked to define the version
    compile("org.jetbrains.kotlin:kotlin-reflect:1.3.31")

    compile("org.glassfish.jersey.core:jersey-server:2.26")
    compile("org.glassfish.jersey.containers:jersey-container-netty-http:2.26")

    //https://stackoverflow.com/questions/44283802/http-status-500-servlet-init/44536542#44536542
    compile("org.glassfish.jersey.inject:jersey-hk2:2.28")
    
    compile("org.glassfish.jersey.media:jersey-media-json-jackson:2.26")
    compile("com.fasterxml.jackson.module:jackson-module-kotlin:2.9.+")

    //For java beyond 9
    compile("javax.xml.bind:jaxb-api:2.2.11")
    compile("com.sun.xml.bind:jaxb-core:2.2.11")
    compile("com.sun.xml.bind:jaxb-impl:2.2.11")
    compile("javax.activation:activation:1.1.1")

    //Exposed. Persistence framework
    compile("org.jetbrains.exposed:exposed:0.13.7")


    runtime("ch.qos.logback:logback-classic:1.1.8")


}

application {
    // Define the main class for the application.
    mainClassName = "com.ciczan.NettyServer"
    
}
